apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2am-gateway-worker
  labels:
    name: wso2am-gateway-worker
spec:
  replicas: 1
  selector:
    name: wso2am-gateway-worker
  template:
    metadata:
      labels:
        name: wso2am-gateway-worker
    spec:
      containers:
      -
        name: wso2am-gateway-worker
        image: wso2/am-gateway-worker-1.9.1:1.0.0
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"